commbank/accounts/urls.py
from django.urls import path
from .views import (
    UserLoginView, LogoutView, profile, bank_statement,
    transfer_money, banking, homeloan, insurance, business,
    investing, security, help, financial_assistance, complaints,
    payment_services, about_us, careers, sustainability, newsroom,
    investor_centre, facebook, linkedin, youtube, instagram,complaints,
    payment_services,
    about_us,
    careers,
    sustainability,
    newsroom,
    investor_centre,
)

app_name = 'accounts'

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="user_login"),
    path("logout/", LogoutView.as_view(), name="user_logout"),
    path('profile/', profile, name='profile'),
    path('bank_statement/', bank_statement, name='bank_statement'),
   # path('transfer_money/', transfer_money, name='transfer_money'),
    path('banking/', banking, name='banking'),
    path('homeloan/', homeloan, name='homeloan'),
    path('insurance/', insurance, name='insurance'),
    path('business/', business, name='business'),
    path('investing/', investing, name='investing'),
    path('facebook/', facebook, name='facebook'),
    path('linkedin/', linkedin, name='linkedin'),
    path('youtube/', youtube, name='youtube'),
    path('instagram/', instagram, name='instagram'),
    path('security/',security,name='security'),
    path('help/',help,name='help'),
    path('financial_assistance',financial_assistance, name='financial_assistance'),
    path('complaints/', complaints, name='complaints'),
    path('payment_services/', payment_services, name='payment_services'),
    path('about_us/', about_us, name='about_us'),
    path('careers/', careers, name='careers'),
    path('sustainability/', sustainability, name='sustainability'),
    path('newsroom/', newsroom, name='newsroom'),
    path('investor_centre/', investor_centre, name='investor_centre'),
]

commbank/banktransactions/urls.py
from django.urls import path

from .views import DepositMoneyView, WithdrawMoneyView, TransferMoneyView, TransactionReportView, LoanView, PersonalLoanView, HomeLoanView, BusinessLoanView, download_statement


app_name = 'banktransactions'



urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),

    path('transfer/',TransferMoneyView.as_view(), name="transfer_money"),

    path('report/', TransactionReportView.as_view(), name="transaction_report"),
    path('loans/', LoanView.as_view(), name="loans"),
    path('personalloan/', PersonalLoanView.as_view(), name='personal_loan'),
    path('homeloan/', HomeLoanView.as_view(), name='home_loan'),
    path('businessloan/', BusinessLoanView.as_view(), name='business_loan'),

    path('download/', download_statement, name='download_statement'),


]

commbank/commbank/urls.py
from django.contrib import admin
from django.urls import path, include

from mainsystem.views import MainBankPageView, HomeView


app_name = 'commbank'
urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('', MainBankPageView.as_view(), name='mainbankpage'),
    path('home/',HomeView.as_view(), name='home'),
    path('banktransactions/',include('banktransactions.urls')),

]

commbank/mainsystem/models.py
from django.db import models

# Create your models here.

commbank/mainsystem/views.py
from django.views.generic import TemplateView
from accounts.models import Account, Transaction
import os
from django.db.models import Sum
import io
from django.http import FileResponse
import matplotlib.pyplot as plt

from django.utils import timezone
from datetime import timedelta

from django.views.generic import TemplateView
from django.utils import timezone
from datetime import timedelta

class HomeView(TemplateView):
    template_name = 'mainsystem/userpage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            # Retrieve the last ten transactions for the current user
            last_ten_transactions = Transaction.objects.filter(user=self.request.user).order_by('-id')[:4]
            context['last_ten_transactions'] = last_ten_transactions
        except Transaction.DoesNotExist:
            # Handle the case where no transactions are found
            context['last_ten_transactions'] = None
            # Log the error or provide a fallback behavior

        # Calculate the date 30 days ago
        thirty_days_ago = timezone.now() - timedelta(days=30)

        # Retrieve all transactions within the last 30 days
        recent_transactions = Transaction.objects.filter(date__gte=thirty_days_ago)

        # Define variables to hold ongoing_amount and incoming_amount
        ongoing_amount = 0
        incoming_amount = 0

        # Loop through each transaction in the recent transactions list
        for transaction in recent_transactions:
            # Check the transaction type and update the corresponding amount variable
            if transaction.transaction_type == 'SENT' or transaction.transaction_type == 'WITHDRAW':
                ongoing_amount += transaction.amount
            elif transaction.transaction_type == 'RECEIVED' or transaction.transaction_type == 'DEPOSIT':
                incoming_amount += transaction.amount

        # Add the calculated amounts and recent transactions to the context
        context['recent_transactions'] = recent_transactions
        context['ongoing_amount'] = ongoing_amount
        context['incoming_amount'] = incoming_amount

        return context




class MainBankPageView(TemplateView):
    template_name = 'mainsystem/index.html'

commbank/templates/mainsystem/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Bank{% endblock %}</title>
    <!-- Include any common CSS files or stylesheets here -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar">

    </nav>

</body>
</html>

commbank/templates/mainsystem/index.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MY Bank</title>

    <link href="{% static 'css/index.css' %}" rel="stylesheet">

</head>

<body>
    <div class="heading-parent">
        <div class="heading-one"><a href="{% url 'accounts:banking' %}">Banking</a></div>
        <div class="heading-two"><a href="{% url 'accounts:homeloan' %}">Home Loans</a></div>
        <div class="heading-three"><a href="{% url 'accounts:insurance' %}">Insurance</a></div>
        <div class="heading-four"><a href="{% url 'accounts:investing' %}">Investing</a></div>
        <div class="heading-five"><a href="{% url 'accounts:business' %}">Business</a></div>
        <a href="{% url 'accounts:user_login' %}" class="button-link">Login</a>
    </div>

    <div class="main-info">
        <div>
            <h1 class="title">My Bank</h1>
            <p class="quote">Invest in your dreams. Secure your future with My Bank</p>
        </div>
        <div>
            <!-- Placeholder for image -->
            <img src="{% static 'images/comm-bank-picture.png' %}" alt="Image" class="img-reduced-width">

        </div>
    </div>

    <div class="bottom-links">

        <div class="contact-us-heading">
            <h1>Contact us</h1>
            <p class="message-us">Message us, ask our virtual assistant, or call to connect to the right help</p>
        </div>

        <div class="quicklinks-parent">
            <div class="quicklink-haeding">QUICK LINKS</div>
            <div class="quicklink-1"><a href="{% url 'accounts:security' %}">Security & scams</a></div>
            <div class="quicklink-2"><a href="{% url 'accounts:help' %}">Help & support</a></div>
            <div class="quicklink-3"><a href="{% url 'accounts:financial_assistance' %}">Financial assistance</a></div>
            <div class="quicklink-4"><a href="{% url 'accounts:complaints' %}">Complaints & compliments</a></div>
            <div class="quicklink-5"><a href="{% url 'accounts:payment_services' %}">Payment services availability</a></div>
        </div>

        <div class="about-us-info">
            <div class="about-us-heading">ABOUT US</div>
            <div class="about-us-1"><a href="{% url 'accounts:about_us' %}">About CommBank</a></div>
            <div class="about-us-2"><a href="{% url 'accounts:careers' %}">Careers at CommBank</a></div>
            <div class="about-us-3"><a href="{% url 'accounts:sustainability' %}">Sustainability</a></div>
            <div class="about-us-4"><a href="{% url 'accounts:newsroom' %}">Newsroom</a></div>
            <div class="about-us-5"><a href="{% url 'accounts:investor_centre' %}">Investor centre</a></div>
        </div>

        <div class="follow-link">
            <div>FOLLOW US</div>
            <div>X</div>
            <div><a href="{% url 'accounts:facebook' %}">Facebook</a></div>
            <div><a href="{% url 'accounts:linkedin' %}">LinkedIn</a></div>
            <div><a href="{% url 'accounts:youtube' %}">YouTube</a></div>
            <div><a href="{% url 'accounts:instagram' %}">Instagram</a></div>
        </div>

    </div>
</body>

</html>

commbank/templates/mainsystem/userpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Banking System</title>
    <link rel="stylesheet" href="{% static 'css/userpage.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> <!-- Include Chart.js -->

</head>
<body>
    <div class="navbar">
        {% if request.user.is_authenticated %}
        <div class="banking-links">
            <h1>My Bank</h1>
            <a href="{% url 'banktransactions:transaction_report' %}" class="link-1" style="font-weight: bold; font-size: 20px;">Transaction Report</a>
            <a href="{% url 'banktransactions:deposit_money' %}" style="font-weight: bold; font-size: 20px;">Deposit Money</a>
            <a href="{% url 'banktransactions:withdraw_money' %}" class="link-3" style="font-weight: bold; font-size: 20px;">Withdraw</a>
            <a href="{% url 'banktransactions:transfer_money' %}" class="link-4" style="font-weight: bold; font-size: 20px;">Transfer Money</a>
            <div class="logout-button">
                <a href="{% url 'accounts:user_logout' %}" class="logout-link" style="font-weight: bold; font-size: 16px;">Logout</a>
            </div>
        </div>

        <div class="acc-details" style="font-weight: bold; font-size: 22px;"></div>

        <div class="user-info">
            <p>Welcome, {{ request.user.userinfo.first_name }} {{ request.user.userinfo.last_name }}</p>
        </div>
        <div class="accbalinfo">
            <p>Your Account's balance is: <span style="font-weight: bold;">{{ request.user.account.balance }}</span></p>
            <p>Hello, User! Your Account Number is: <span style="font-weight: bold;">{{ request.user.account.account_number }}</span></p>
            <p>Your BSB Number is: <span style="font-weight: bold;">{{ request.user.branchinfo.BSB_number }}</span></p>
        </div>
        <div class="container">
            <div class="caption"c>Visualizing Financial Activity: Outflows and Inflows</div>
            <div class="chart">
                <canvas id="transactionChart" width="400" height="400"></canvas>
            </div>
        </div>
            <div class="transactions">
                <h2>Recent Transactions</h2>
                <ul class="transactionlist">
                    {% for transaction in last_ten_transactions %}
                        <li class="listelements">
                            <table>
                                <tr>
                                    <td>Amount:</td>
                                    <td>{{ transaction.amount }}</td>
                                </tr>
                                <tr>
                                    <td>Type:</td>
                                    <td>{{ transaction.transaction_type }}</td>
                                </tr>
                                <tr>
                                    <td>From:</td>
                                    <td>{{ transaction.first_account_number }}</td>
                                </tr>
                                <tr>
                                    <td>To:</td>
                                    <td>{{ transaction.second_account_number }}</td>
                                </tr>
                                <tr>
                                    <td>Date:</td>
                                    <td>{{ transaction.date }}</td>
                                </tr>
                            </table>
                        </li>
                    {% endfor %}
                </ul>
            </div>


            <div class="sidebar">
                <section class="services">
                    <div class="loan box">
                        <img src="{% static 'images/loans1.jpg' %}" alt="Loan">
                        <a href="{% url 'banktransactions:loans' %}">Loans</a>
                    </div>
                </section>
                <section class="services">
                    <div class="cards box">
                        <img src="{% static 'images/cards.jpg' %}" alt="Cards">
                        <a href="#">Cards</a>
                    </div>
                </section>
                <section class="services">
                    <div class="mutualfund box">
                        <img src="{% static 'images/insurance.jpg' %}" alt="Insurance">
                        <a href="#">Insurance</a>
                    </div>
                </section>
                <section class="services">
                    <div class="billplay box">
                        <img src="{% static 'images/billpay.png' %}" alt="BillPay & Recharge">
                        <a href="#">BillPay & Recharge</a>
                    </div>
                </section>

            </div>

            <footer>
                <p>Copyright My Bank Ltd.</p>
                <div class="footer-links">
                    <a href="#">Terms and Conditions</a>
                    <span>|</span>
                    <a href="#">Privacy Policy</a>
                </div>
            </footer>


        {% else %}
        <div class="login-button">
            <a href="{% url 'accounts:user_login' %}" class="login-link">Login</a>
        </div>
        {% endif %}
    </div>

    <script>
        var ctx = document.getElementById('transactionChart').getContext('2d');

        // Define the data for the donut chart
        var data = {
            labels: ['Expenses', 'Income'],
            datasets: [{
                data: [{{ ongoing_amount }}, {{ incoming_amount }}],
                backgroundColor: [ 'rgba(255, 99, 132, 0.5)', 'rgba(54, 162, 235, 0.5)'],
                borderColor: ['rgba(255, 99, 132, 1)', 'rgba(54, 162, 235, 1)' ],
                borderWidth: 1
            }]
        };

        // Define the options for the donut chart
        var options = {
            responsive: true,
            maintainAspectRatio: false,
            title: {
                display: true,
                text: 'Transaction Distribution'
            }
        };

        // Create the donut chart
        var myChart = new Chart(ctx, {
            type: 'doughnut',
            data: data,
            options: options
        });

        // Output the calculated ongoing_amount and incoming_amount to the console
        console.log('Ongoing Amount:', {{ ongoing_amount }});
        console.log('Incoming Amount:', {{ incoming_amount }});
        console.log('Hello');
    </script>





</body>
</html>